// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Data.Entities
{
    public partial class Student
    {
        public Student()
        {
            Users = new HashSet<Users>();
        }

        [Key]
        public int StudentId { get; set; }
        [StringLength(50)]
        public string CourseId { get; set; }
        [Required]
        [StringLength(150)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(150)]
        public string LastName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BirthDate { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("Student")]
        public virtual Course Course { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<Users> Users { get; set; }
    }
}