// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KUSYS_Demo.Data.Entities
{
    public partial class Users
    {
        [Key]
        public int Id { get; set; }
        public int? StudentId { get; set; }
        public int? RoleId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Password { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("Users")]
        public virtual Roles Role { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("Users")]
        public virtual Student Student { get; set; }
    }
}